# GitHub action for removing dangling Docker containers using the
# naming convention <repo>__<workflow>__<job>__<timestamp>.
name: clean_dangling_docker

inputs:
    age:
        default: 86400

runs:
    using: composite
    steps:
      - name: 🐋 Clean dangling Docker containers
        run: |
            for container in $( \
                docker ps \
                    -a -f "name=${GITHUB_REPOSITORY//\//_}__${GITHUB_WORKFLOW}__${GITHUB_JOB}" \
                | tail -n +2 | awk '{print $NF}' \
            ); do
                t="${container##*__}"
                dt=$(($(date +%s) - t))
                if [ ${dt} -gt ${{ inputs.age }} ]; then
                    echo "removing Docker container ${container}"
                    docker rm -f "${container}" >/dev/null 2>&1 || :
                fi
            done
        shell: bash

