# GitHub workflow for testing the entire build,
# including installation, the test suite and building of the documentation.
# - This workflow runs on a schedule, and only if
#   the GitHub secret SCHEDULE_BUILD is set to True.
name: build

on:
    schedule:
      - cron: '0 0 * * SUN'  # Weekly, Sundays at 00:00

jobs:
    check_schedule:
        runs-on: ubuntu-20.04
        outputs:
            scheduled: ${{ steps.check_schedule.outputs.scheduled }}
        steps:
          - name: 📝 Check schedule
            id: check_schedule
            env:
                schedule_build: ${{ secrets.SCHEDULE_BUILD }}
            run: |
                if [ "${schedule_build}" == "True" ]; then
                    echo "Build scheduled"
                    echo "::set-output name=scheduled::1"
                else
                    echo "Build not scheduled"
                fi
    build:
        runs-on: ubuntu-20.04
        needs: check_schedule
        if: needs.check_schedule.outputs.scheduled
        steps:
          - name: 🛎 Checkout
            uses: actions/checkout@v2
          - name: 🐋 Clean dangling Docker containers
            uses: ./.github/actions/clean-dangling-docker
          - name: 🔧 Install
            run: |
                echo ".git"      >> .dockerignore
                echo ".reusable" >> .dockerignore
                echo ".tmp"      >> .dockerignore
                echo "build"     >> .dockerignore
                echo "dep"       >> .dockerignore
                echo "ic"        >> .dockerignore
                echo "job"       >> .dockerignore
                echo "output"    >> .dockerignore
                docker build \
                    -t concept:latest \
                    --force-rm \
                    --no-cache \
                    --pull \
                    .
          - name: 🤖 Run test suite
            run: |
                sleep 1
                docker run \
                    -e make_jobs="-j 1" \
                    --name "${GITHUB_REPOSITORY//\//_}__${GITHUB_WORKFLOW}__${GITHUB_JOB}__$(date +%s)" \
                    --rm concept:latest \
                    concept -t all
          - name: 📖 Build documentation
            run: |
                sleep 1
                docker run \
                    --name "${GITHUB_REPOSITORY//\//_}__${GITHUB_JOB}__$(date +%s)" \
                    --rm \
                    concept:latest \
                    bash -c 'make clean_doc && make doc'

